import {
  Baby,
  Backpack,
  Bath,
  Clapperboard,
  Droplets,
  Dumbbell,
  HandHeart,
  Heater,
  MountainSnow,
  PawPrint,
  Snowflake,
  Utensils,
  BedDouble,
  CarFront,
  ChefHat,
  Coffee,
  ConciergeBell,
  CookingPot,
  Flame,
  House,
  MapPin,
  Mountain,
  Plane,
  PlugZap,
  Shirt,
  ShoppingBasket,
  Sparkles,
  SprayCan,
  Sun,
  TreePine,
  Tv,
  WashingMachine,
  WavesLadder,
  Wifi,
  type LucideIcon,
} from 'lucide-react'

// Ordre significatif : les termes précis passent avant les termes larges (« lave-linge » avant « linge »).
const featureIcons: Array<[string[], LucideIcon]> = [
  // Spec 086 AC-04 : icône dédiée pour chaque équipement / service du catalogue.
  [['lave-vaisselle'], Utensils],
  [['lave-linge'], WashingMachine],
  [['jacuzzi', 'spa privatif'], Bath],
  [['sauna', 'hammam'], Droplets],
  [['massage', 'spa'], HandHeart],
  [['cinéma'], Clapperboard],
  [['salle de sport', 'fitness'], Dumbbell],
  [['climatisation'], Snowflake],
  [['chauffage'], Heater],
  [['ski'], MountainSnow],
  [['animaux', 'animal'], PawPrint],
  [['bébé', 'enfant'], Baby],
  [['location de matériel', 'matériel'], Backpack],
  [['chambre', 'lit', 'couchage'], BedDouble],
  [['salle de bain'], Bath],
  [['wi-fi', 'wifi'], Wifi],
  [['petit-déjeuner', 'petit déjeuner', 'petit-dejeuner'], Coffee],
  [['transfert aéroport', 'transfert'], Plane],
  [['ménage', 'nettoyage'], SprayCan],
  [['conciergerie', 'concierge'], ConciergeBell],
  [["courses à l'arrivée", 'courses à l’arrivée', 'courses'], ShoppingBasket],
  [['piscine'], WavesLadder],
  [['recharge'], PlugZap],
  [['parking'], CarFront],
  [['barbecue', 'cheminée'], Flame],
  [['cuisine'], CookingPot],
  [['linge', 'serviette'], Shirt],
  [['chef'], ChefHat],
  [['café'], Coffee],
  [['terrasse', 'balcon'], Sun],
  [['montagne'], Mountain],
  [['lave-linge'], WashingMachine],
  [['télévision', 'tv'], Tv],
  [['proximité', 'centre'], MapPin],
  [['extérieur', 'jardin'], TreePine],
  [['maison', 'chalet'], House],
]

/** Résout une icône Lucide sémantique pour un équipement/service (fallback Sparkles). */
export function featureIconFor(item: string): LucideIcon {
  const normalized = item.toLocaleLowerCase('fr')
  return (
    featureIcons.find(([terms]) => terms.some(term => normalized.includes(term)))?.[1] ??
    Sparkles
  )
}
