import type { GuidePoi, GuidePoiCategory } from '@/features/guide-app/types'

const categories = {
  restaurant: {
    slug: 'diner',
    name: 'Restaurants',
    icon: 'utensils',
    color: '#db2777',
  },
  shop: {
    slug: 'alimentation',
    name: 'Commerces utiles',
    icon: 'shopping-basket',
    color: '#d97706',
  },
  culture: {
    slug: 'culture',
    name: 'Culture',
    icon: 'landmark',
    color: '#7c3aed',
  },
  activity: {
    slug: 'activite',
    name: 'Activités',
    icon: 'ticket',
    color: '#2563eb',
  },
  family: {
    slug: 'famille',
    name: 'En famille',
    icon: 'users',
    color: '#059669',
  },
  care: {
    slug: 'soin',
    name: 'Bien-être',
    icon: 'sparkles',
    color: '#be185d',
  },
  walk: {
    slug: 'rando',
    name: 'Balades',
    icon: 'mountain',
    color: '#15803d',
  },
} satisfies Record<string, GuidePoiCategory>

function directions(latitude: number, longitude: number) {
  return `https://www.google.com/maps/dir/?api=1&destination=${latitude},${longitude}`
}

export const demoPois: GuidePoi[] = [
  {
    id: 'demo-poi-rond-de-carotte',
    isOpenNow: true,
    name: 'Rond de Carotte',
    slug: 'rond-de-carotte',
    category: categories.restaurant,
    description:
      'Un restau-cave chaleureux qui propose brunchs, déjeuners, cafés et pâtisseries maison, avec une belle sélection de vins.',
    shortDescription: 'Cuisine maison, brunch et cave au cœur du village.',
    photos: [
      'https://cftqqyqfhlvobtsatxdq.supabase.co/storage/v1/object/public/guide-photos/pois/1782132327133.avif',
      'https://static.wixstatic.com/media/90a441_f2231b6f47ac4f62bf3b744c42cee73b~mv2.jpg/v1/fill/w_283,h_100,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/90a441_f2231b6f47ac4f62bf3b744c42cee73b~mv2.jpg',
    ],
    latitude: 45.893744,
    longitude: 6.711702,
    address: '50 rue de la Vignette, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 4 min',
    durationLabel: '1 h 30',
    recommended: true,
    website: 'https://www.ronddecarotte.com/',
    phone: '04 50 47 76 39',
    directionsUrl: directions(45.893744, 6.711702),
    rating: 4.8,
  },
  {
    id: 'demo-poi-bistrotserac',
    isOpenNow: true,
    name: 'Bistrotsérac',
    slug: 'bistrotserac',
    category: categories.restaurant,
    description:
      'Sur la place du village, une table conviviale autour de la cuisson à la braise et de produits soigneusement sélectionnés.',
    shortDescription: 'Cuisine à la braise sur la place du village.',
    photos: ['https://www.3serac.fr/media/cache/jadro_resize/rc/FjUHU7lg1755510540/jadroRoot/medias/68077ec88354f/atelier-boris-molinier-lou-broche-2278.jpg'],
    latitude: 45.892444,
    longitude: 6.711432,
    address: '38 avenue du Mont Paccard, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 3 min',
    durationLabel: '1 h 30',
    website: 'https://www.3serac.fr/',
    phone: '04 50 98 43 35',
    directionsUrl: directions(45.892444, 6.711432),
    rating: 4.4,
  },
  {
    id: 'demo-poi-communailles',
    isOpenNow: false,
    name: 'Le Relais des Communailles',
    slug: 'le-relais-des-communailles',
    category: categories.restaurant,
    description:
      'Une adresse de montagne conviviale face au Mont-Blanc, appréciée pour son panorama et son atmosphère chaleureuse.',
    shortDescription: 'Une table panoramique face au Mont-Blanc.',
    photos: [
      'https://lerelaisdescommunailles.com/wp-content/uploads/2024/02/7H2A7789-scaled.jpg',
      'https://lerelaisdescommunailles.com/wp-content/uploads/2023/12/7H2A7507-2-scaled.jpg',
    ],
    latitude: 45.864073,
    longitude: 6.687634,
    address: '1635 route des Communailles, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 18 min',
    durationLabel: '2 h',
    recommended: true,
    website: 'https://lerelaisdescommunailles.com/',
    phone: '04 50 21 67 70',
    directionsUrl: directions(45.864073, 6.687634),
    rating: 4.9,
  },
  {
    id: 'demo-poi-petit-biscuit',
    isOpenNow: true,
    name: 'Boulangerie Petit Biscuit La Patinoire',
    slug: 'boulangerie-petit-biscuit-la-patinoire',
    category: categories.shop,
    description:
      'Pains, viennoiseries et pâtisseries artisanales à quelques pas de la patinoire.',
    shortDescription: 'La pause gourmande près de la patinoire.',
    photos: ['https://static.apidae-tourisme.com/filestore/objets-touristiques/images/246/232/41609462.jpg'],
    latitude: 45.888729,
    longitude: 6.712794,
    address: '28 impasse de la Cascade, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 5 min',
    durationLabel: '20 min',
    familyFriendly: true,
    website:
      'https://www.saintgervais.com/jai-envie/commerces-services/boulangerie-petit-biscuit-la-patinoire-saint-gervais-les-bains-fr-5172484/',
    directionsUrl: directions(45.888729, 6.712794),
  },
  {
    id: 'demo-poi-carrefour-express',
    isOpenNow: true,
    name: 'Carrefour Express',
    slug: 'carrefour-express',
    category: categories.shop,
    description:
      'Un commerce de proximité pratique pour les courses quotidiennes et les produits essentiels.',
    shortDescription: 'Les courses essentielles en plein centre.',
    photos: ['/fallback/fallback-alimentation.png'],
    latitude: 45.892358,
    longitude: 6.712075,
    address: '28 rue du Mont Blanc, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 3 min',
    durationLabel: '20 min',
    nearby: true,
    website: 'https://www.carrefour.fr/magasin/express-saint-gervais',
    phone: '04 50 47 94 74',
    directionsUrl: directions(45.892358, 6.712075),
    rating: 4.1,
  },
  {
    id: 'demo-poi-hautetour',
    isOpenNow: true,
    name: 'Maison forte de Hautetour',
    slug: 'maison-forte-de-hautetour',
    category: categories.culture,
    description:
      'Cette bâtisse du XIIIe siècle raconte l’histoire de l’alpinisme et accueille des expositions temporaires et des activités familiales.',
    shortDescription: 'Patrimoine, alpinisme et expositions.',
    photos: [
      'https://static.apidae-tourisme.com/filestore/objets-touristiques/images/60/198/37209660.jpg',
      'https://static.apidae-tourisme.com/filestore/objets-touristiques/images/2/90/30956034.jpg',
    ],
    latitude: 45.892541,
    longitude: 6.713033,
    address: '114 passage Montjoux, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 5 min',
    durationLabel: '1 h',
    recommended: true,
    familyFriendly: true,
    website:
      'https://www.saintgervais.com/je-minspire/vie-culturelle/maison-forte-de-hautetour-saint-gervais-les-bains-fr-4247482/',
    phone: '04 50 47 78 95',
    directionsUrl: directions(45.892541, 6.713033),
    rating: 4.4,
  },
  {
    id: 'demo-poi-la-cure',
    isOpenNow: false,
    name: 'La Cure',
    slug: 'la-cure',
    category: categories.culture,
    description:
      'Le pôle culturel du village réunit expositions, bibliothèque de montagne, ateliers et conférences.',
    shortDescription: 'Le nouveau pôle culturel de Saint-Gervais.',
    photos: ['https://static.apidae-tourisme.com/filestore/objets-touristiques/images/31/195/37208863.jpg'],
    latitude: 45.892227,
    longitude: 6.710875,
    address: '15 avenue du Mont Paccard, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 2 min',
    durationLabel: '1 h',
    familyFriendly: true,
    website:
      'https://www.saintgervais.com/je-minspire/vie-culturelle/la-cure-saint-gervais-les-bains-fr-4247479/',
    phone: '04 50 47 78 95',
    directionsUrl: directions(45.892227, 6.710875),
    rating: 4.8,
  },
  {
    id: 'demo-poi-tramway',
    isOpenNow: true,
    name: 'Tramway du Mont-Blanc',
    slug: 'tramway-du-mont-blanc',
    category: categories.activity,
    description:
      'Le train à crémaillère emblématique monte du Fayet vers les paysages d’altitude au pied du Mont-Blanc.',
    shortDescription: 'Le train mythique vers le Nid d’Aigle.',
    photos: ['https://www.tramwaydumontblanc.fr/app/uploads/2026/04/Gare_de_Saint-Gervais_du_Tramway_du_Mont-Blanc-Hugo_GUILLEREZ-13658-1200px-1.jpg'],
    latitude: 45.897875,
    longitude: 6.711024,
    address: '571 rue du Mont Lachat, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 9 min',
    durationLabel: 'Demi-journée',
    recommended: true,
    familyFriendly: true,
    website: 'https://www.tramwaydumontblanc.fr/',
    directionsUrl: directions(45.897875, 6.711024),
    rating: 4,
  },
  {
    id: 'demo-poi-bettex',
    isOpenNow: false,
    name: 'Télécabine de l’Alpin — Le Bettex',
    slug: 'telecabine-le-bettex',
    category: categories.activity,
    description:
      'Une montée rapide vers le plateau du Bettex et son panorama spectaculaire sur le massif du Mont-Blanc.',
    shortDescription: 'Accès panoramique au plateau du Bettex.',
    photos: ['https://woody.cloudly.space/app/uploads/saint-gervais/2023/07/thumbs/DSC01791-1920x960.jpg'],
    latitude: 45.891922,
    longitude: 6.713623,
    address: '201 avenue du Mont d’Arbois, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 5 min',
    durationLabel: 'Demi-journée',
    familyFriendly: true,
    website:
      'https://www.saintgervais.com/jai-envie/activites/telecabine-de-lalpin-saint-gervais-le-bettex-saint-gervais-les-bains-fr-4247190/',
    directionsUrl: directions(45.891922, 6.713623),
    rating: 4.5,
  },
  {
    id: 'demo-poi-piscine',
    isOpenNow: true,
    name: 'Piscine de Saint-Gervais',
    slug: 'piscine-de-saint-gervais',
    category: categories.family,
    description:
      'Un centre aquatique avec bassin de nage, espace ludique, pataugeoire et bassin extérieur en saison.',
    shortDescription: 'Bassins et espace ludique pour toute la famille.',
    photos: ['/fallback/fallback-piscine.png'],
    latitude: 45.884329,
    longitude: 6.715136,
    address: '798 avenue de Miage, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 8 min',
    durationLabel: '2 h',
    familyFriendly: true,
    website:
      'https://www.saintgervais.com/jai-envie/activites/piscine-de-saint-gervais-saint-gervais-les-bains-fr-4247613/',
    phone: '04 50 93 42 87',
    directionsUrl: directions(45.884329, 6.715136),
  },
  {
    id: 'demo-poi-parc-thermal',
    name: 'Parc thermal du Fayet',
    slug: 'parc-thermal-du-fayet',
    category: categories.family,
    description:
      'Un grand parc arboré au bord du Bonnant, agréable pour une promenade, une pause ou une sortie avec les enfants.',
    shortDescription: 'Une promenade fraîche et ombragée au Fayet.',
    photos: ['/fallback/fallback-famille.png'],
    latitude: 45.906164,
    longitude: 6.706591,
    address: 'Parc thermal, Le Fayet, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 12 min',
    durationLabel: '1 h',
    familyFriendly: true,
    nearby: true,
    website: 'https://www.saintgervais.com/',
    directionsUrl: directions(45.906164, 6.706591),
  },
  {
    id: 'demo-poi-thermes',
    isOpenNow: true,
    name: 'Les Thermes de Saint-Gervais Mont Blanc',
    slug: 'thermes-de-saint-gervais',
    category: categories.care,
    description:
      'Un établissement thermal historique et un spa installés au fond du Parc thermal du Fayet.',
    shortDescription: 'Eau thermale, soins et détente au pied du Mont-Blanc.',
    photos: ['https://www.thermes-saint-gervais.com/include/images/Menu_Sejours_Sante.jpg'],
    latitude: 45.896529,
    longitude: 6.70612,
    address: '355 allée du Docteur Lépinay, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 8 min',
    durationLabel: 'Demi-journée',
    website: 'https://www.thermes-saint-gervais.com/',
    directionsUrl: directions(45.896529, 6.70612),
    rating: 3.9,
  },
  {
    id: 'demo-poi-pont-du-diable',
    name: 'Pont du Diable',
    slug: 'pont-du-diable',
    category: categories.walk,
    description:
      'Ce pont historique de 1876 surplombe les gorges du Bonnant et offre un point de vue saisissant.',
    shortDescription: 'Un ouvrage historique au-dessus des gorges.',
    photos: ['/fallback/fallback-rando.png'],
    latitude: 45.88841,
    longitude: 6.714553,
    address: 'Pont du Diable, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 6 min',
    durationLabel: '30 min',
    familyFriendly: true,
    website:
      'https://www.saintgervais.com/je-minspire/vie-culturelle/pont-du-diable-saint-gervais-les-bains-fr-4247721/',
    directionsUrl: directions(45.88841, 6.714553),
  },
  {
    id: 'demo-poi-porcherey',
    name: 'L’Alpage de Porcherey',
    slug: 'alpage-de-porcherey',
    category: categories.walk,
    description:
      'Une randonnée vers un alpage paisible avec de beaux points de vue sur l’Aiguille de Bionnassay et les Dômes de Miage.',
    shortDescription: 'Forêts, clairières et panorama sur le massif.',
    photos: ['https://static.apidae-tourisme.com/filestore/objets-touristiques/images/181/221/31382965.jpg'],
    latitude: 45.863934,
    longitude: 6.717467,
    address: 'Départ à Saint-Nicolas de Véroce, 74170 Saint-Gervais-les-Bains',
    distanceLabel: 'À 17 min',
    durationLabel: '3 h 30',
    recommended: true,
    website:
      'https://www.saintgervais.com/je-minspire/randonnee-toutes-saisons/les-chalets-de-porcherey-au-depart-du-plateau-de-la-croix-saint-gervais-les-bains-fr-5704123/',
    directionsUrl: directions(45.863934, 6.717467),
    trail: {
      difficulty: 'easy',
      estimatedDurationMinutes: 210,
      distanceKm: 8.3,
      elevationGainM: 709,
      startLabel: 'Saint-Nicolas de Véroce',
      trackingEnabled: false,
    },
  },
]
